FROM uhub.service.ucloud.cn/openbayes_algopub/pytorch-tvm:1.11.0-tvm0.9.0-cu113.81
RUN pip install mmtrack
RUN pip install seaborn thop
COPY ./ /code/
RUN cd /code/ && pip install -r requirements.txt
WORKDIR /code
# sudo docker run --gpus 'device=1' --rm --name tracking -v /home/jianghan/tracking/test_input:/input tracking python run.py --input_path /input/VID_20220727_175808.mp4 --counter_path /input/counter.json